### ISSUE TITLE
App crashing due to 'Library not loaded'

### ISSUE THREAD

**Issue by MoSchaub** [macmade/QEMU-Manager#11] opened 2023-01-21 22:49 UTC
I cloned the repo including submodules and set up code signing. It compiles fine. But when I try to run it. I am running into the following error: 
`dyld[7574]: Library not loaded: '@rpath/GitHubUpdates.framework/Versions/A/GitHubUpdates'`

**Comment by macmade** [comment] 2023-01-24 11:18
I cannot reproduce the issue with a fresh clone and using a different signing certificate.  
Please add additional details.

**Comment by macmade** [comment] 2023-02-03 00:19
No feedback, closing…

**Closed as completed by macmade** 2023-02-03 00:19 UTC
